sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

env:
  - CASSANDRA_CLUSTER_HOSTS=localhost APP_PORT=2551

language: scala

services:
  - docker

scala: 2.12.10

install:
  - nvm install node
  - npm install newman

jdk:
- openjdk14

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

  - ./run_travis.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" == "push-to-dockerhub-from-travis" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    sbt -batch hmda-platform/docker:publishLocal
    docker tag hmda/hmda-platform:latest hmda/hmda-platform:latest
    docker push hmda/hmda-platform:latest
    fi
  - bash <(curl -s https://codecov.io/bash)
