apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hmda-data-publisher.name" . }}-dynamic-schedule-config
data:
  LAR_PUBLIC_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  LAR_PUBLIC_SCHEDULE_YEARS: 2020,2021,2022
  LAR_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  LAR_SCHEDULE_YEARS: 2020,2021,2022
  LAR_QUARTERLY_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  LAR_QUARTERLY_SCHEDULE_YEARS: 2020,2021,2022
  LAR_LOAN_LIMIT_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  LAR_LOAN_LIMIT_SCHEDULE_YEARS: 2020,2021,2022
  PANEL_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  PANEL_SCHEDULE_YEARS: 2020,2021,2022
  TS_PUBLIC_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  TS_PUBLIC_SCHEDULE_YEARS: 2020,2021,2022
  TS_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  TS_SCHEDULE_YEARS: 2020,2021,2022
  TS_QUARTERLY_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  TS_QUARTERLY_SCHEDULE_YEARS: 2020,2021,2022
#  TS_ANNUAL_SUFFIXES: 2019:_one_year_04052022,2020:_one_year_04302022,2021:_snapshot_04302022
#  LAR_ANNUAL_SUFFIXES: 2019:_one_year_04052022,2020:_one_year_04302022,2021:_snapshot_04302022