apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ include "hmda-quarterly-data-service.fullname" . }}_mapping
      ambassador_id: ambassador-default-1
      prefix: /quarterly-data/
      rewrite: /
      service: {{ include "hmda-quarterly-data-service.fullname" . }}:{{ .Values.service.port }}
  labels:
    {{- include "hmda-quarterly-data-service.labels" . | nindent 4 }}
  name: {{ include "hmda-quarterly-data-service.fullname" . }}-ambassador
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  sessionAffinity: None
  type: ClusterIP