apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hmda-quarterly-data-service.fullname" . }}-verbiage-configmap
data:
  GRAPH_SUMMARY: The following graphs represent data for the 55 financial institutions reporting HMDA quarterly data in the current year. The graphs display current quarters and three years of historical data.