apiVersion: v1
kind: ConfigMap
metadata:
  name: timed-guards
data:
  yearsAllowed: "2019,2020,2021"
  currentYear: "2020"
  quarterlyYearsAllowed: "2020,2021"
  q1Start: "December 10"
  q1End: "June 30"
  q2Start: "July 01"
  q2End: "September 30"
  q3Start: "October 01"
  q3End: "December 31"