---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: hmda-reporting
  type: ClusterIP
  ports:
  - name: {{ .Values.reporting.name }}
    protocol: {{ .Values.reporting.protocol }}
    port: {{ .Values.reporting.port }}
    targetPort: {{ .Values.reporting.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-hmda-reporting
  name: ambassador-hmda-reporting
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind: Mapping
      name: hmda_reporting_mapping
      ambassador_id: ambassador-default-1
      prefix: /v2/reporting/
      service: {{ .Values.service.name }}:{{ .Values.reporting.port }}
      timeout_ms: 180000
      retry_policy:
        num_retries: 10
        retry_on: 5xx
      labels:
        ambassador:
         - string_request_label:
           - hmda-reporting
spec:
  clusterIP: None
