name: HMDA PR CVE Scan

on:
  pull_request:
    types: [opened, synchronize, reopened] # to run the scan on each push and reopens

jobs:
  hmda-platform-cve-scan:
    runs-on: macos-latest
    env:
      IMAGE_NAME: pr-cve-scan
      IMAGE_TAG: latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          brew install docker

      - name: Build image of HMDA platform
        run: |
          sbt "project hmda-platform" dockerPublishLocalSkipTests
        continue-on-error: true

      - name: Tag Docker image
        run: docker tag $(docker images --filter=reference="hmda/hmda-platform:$IMAGE_TAG" --format "{{.ID}}") hmda-cve/hmda-platform:$IMAGE_NAME

      - name: Install Grype
        run: |
          brew install grype

      - name: Run Grype scan
        run: |
          grype hmda-cve/hmda-platform:$IMAGE_NAME

      - name: Remove Docker image
        run: |
          docker rmi hmda-cve/hmda-platform:$IMAGE_NAME