name: HMDA PR CVE Scan

on:
  pull_request:
    types: [opened, synchronize, reopened] # to run the scan on each push and reopens

jobs:
  hmda-platform-cve-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4