name: HMDA PR CVE Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  hmda-platform-cve-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build Docker image of HMDA platform
        run: |
          env JAVA_OPTS="-Xss256m -Xmx4096m" sbt "project hmda-platform" dockerPublishLocalSkipTests
        continue-on-error: false

      - name: Tag and name Docker image
        run: docker tag hmda/hmda-platform:latest pr-cve-scan:latest

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Make directory for reports
        run: mkdir -p ~/artifact/reports

      - name: Install Grype
        run: |
          brew install grype

      - name: Run Grype scan
        run: |
          grype pr-cve-scan:latest -o json > grype-report.json

      - name: Move Grype report to directory
        run: mv grype-report.json ~/artifact/reports/

      - name: Store Grype report in a variable
        id: store_grype_report
        run: |
          report=$(sed ':a;N;$!ba;s/\n/\\n/g' ~/artifact/reports/grype-report.json)
          echo "::set-output name=g_report::$report"

      - name: Display Grype results on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Grype CVE Report**
            ${{ steps.store_grype_report.outputs.g_report }}

      - name: Remove Docker image
        run: |
          docker rmi pr-cve-scan:latest